#!/bin/bash

SUBMODS=$(ls -p | grep "ui-.*/")

# DIRECTORIES
BUILDINGS_DIR="common/buildings"
STRATEGIC_RESOURCES_DIR="common/strategic_resources"
SYSTEM_INITIALISERS_DIR="common/solar_system_initializers"
DEPOSIT_BLOCKERS_DIR="common/deposit_blockers"

# INITIALISATIONS
BUILDINGS_COUNT=0
STRATEGIC_RESOURCES_COUNT=0
SYSTEM_INITIALISERS_COUNT=0
DEPOSIT_BLOCKERS_COUNT=0

# COUNT ADDITIONS
for SUBMOD in $SUBMODS; do

    if [ -d $SUBMOD/$GALAXY_SIZES_DIR ]; then
        GALAXY_SIZES_COUNT_SUBMOD=$(ls $SUBMOD/$GALAXY_SIZES_DIR | wc -l)
        GALAXY_SIZES_COUNT=$((GALAXY_SIZES_COUNT + GALAXY_SIZES_COUNT_SUBMOD))
    fi

    if [ -d $SUBMOD/$SYSTEM_INITIALISERS_DIR ]; then
        SYSTEM_INITIALISERS_COUNT_SUBMOD=$(ls $SUBMOD/$SYSTEM_INITIALISERS_DIR | wc -l)
        SYSTEM_INITIALISERS_COUNT=$((SYSTEM_INITIALISERS_COUNT + SYSTEM_INITIALISERS_COUNT_SUBMOD))
    fi
done

# PRINT RESULTS
echo "Buildings:" $BUILDINGS_COUNT
echo "Strategic resources:" $STRATEGIC_RESOURCES_COUNT
echo "System initialisers:" $SYSTEM_INITIALISERS_COUNT
echo "Deposit blockers:" $DEPOSIT_BLOCKERS_COUNT
